"""Changed tables

Revision ID: 6cdaf8b6c3e2
Revises: ecdd2b7a0f05
Create Date: 2025-04-10 07:46:53.090508

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6cdaf8b6c3e2'
down_revision = 'ecdd2b7a0f05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
