"""Changed tables

Revision ID: ade62e81521e
Revises: 6cdaf8b6c3e2
Create Date: 2025-04-10 08:03:37.150252

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ade62e81521e'
down_revision = '6cdaf8b6c3e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
